image: &default_image quay.io/redsift/ingraind-build:20.04

version: 2.1
commands:
  setup_ubuntu_env:
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init

jobs:
  build_doc_and_bin:
    parameters:
      tag:
        type: string
        default: "latest"
    working_directory: /build
    resource_class: large
    docker:
      - image: quay.io/redsift/ingraind-build:<< parameters.tag >>
    steps:
      - setup_ubuntu_env
      - run:
          name: Build
          command: |
            export KERNEL_SOURCE=/usr/src/kernels/$(rpm -qa kernel-devel || true |cut -d- -f3-)/
            if [ "x$KERNEL_SOURCE" = "x/usr/src/kernels//" ]; then
                export KERNEL_SOURCE=/lib/modules/$(ls /lib/modules |head -n1)/build/
            fi
            cargo build
            cargo test --bins --tests
            RUSTDOCFLAGS="-C panic=abort" cargo test --doc --workspace src
            cargo doc --no-deps

  publish:
    docker:
      - image: *default_image
    steps:
      - setup_ubuntu_env
      - run:
          name: Publish package
          command: |
            rustup default nightly
            git config --global url."https://$GITHUB_HTTP_TOKEN:@github.com".insteadOf "https://github.com"
            cargo login $CRATES_KEY
            for package in bpf-sys redbpf{,-macros,-probes} cargo-bpf; do
              pushd $package
              cargo publish || true
              popd
              sleep 5
            done

            cargo doc --no-deps --release

            git config --global user.email "team@redsift.com"
            git config --global user.name "CircleCI bot"
            git clone https://$GITHUB_HTTP_TOKEN:@github.com/redsift/ingraind.org publish
            rm -rf publish/api/
            mkdir -p publish/api/
            cp -r target/doc/* publish/api/
            >publish/api/index.html echo '<meta http-equiv="refresh" content="0; url=https://ingraind.org/api/redbpf/" />'
            cd publish
            git add *
            git commit -a -m '[CI] Update redbpf docs'
            git push

workflows:
  version: 2
  build_publish:
    jobs:
      - build_doc_and_bin:
          context: org-global
          name: "ubuntu 18.04"
          tag: "18.04"
          filters:
            tags:
              only: /.*/
      - build_doc_and_bin:
          context: org-global
          name: "ubuntu 20.04"
          tag: "20.04"
          filters:
            tags:
              only: /.*/
      - build_doc_and_bin:
          context: org-global
          name: "fedora 32"
          tag: "fedora"
          filters:
            tags:
              only: /.*/
      - publish:
          context: org-global
          requires:
            - "ubuntu 18.04"
            - "ubuntu 20.04"
            - "fedora 32"
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
