[package]
name = "redbpf-macros"
version = "0.9.0"
edition = '2018'

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = {version = "1.0", features = ["full"] }
quote = "1.0"

[build-dependencies]
redbpf = { version = "^0.9.0", features = ["build"], path = "../redbpf" }
bindgen = "0.51"
syn = {version = "1.0", features = ["full", "visit-mut"] }
quote = "1.0"
