[package]
name = "example-userspace"
version = "0.1.0"
authors = ["Junyeong Jeong <rhdxmr@gmail.com>"]
edition = "2018"

[build-dependencies]
cargo-bpf = { version = "", path = "../../cargo-bpf", default-features = false, features = ["build"] }

[[example]]
name = "vfsreadlat"
path = "src/bin/vfsreadlat.rs"

[dependencies]
probes = { path = "../example-probes", package = "example-probes" }
libc = ""
tokio = { version = "", features = ["signal", "time"] }
redbpf = { version = "", path = "../../redbpf", features = ["load"] }
futures = ""
