[package]
name = "redbpf-probes"
version = "0.1.0"
edition = '2018'

[dependencies]
cty = "0.2"

[build-dependencies]
bindgen = "0.51.1"
redbpf = { version = "0.3.3", features = ["build"], path = "../redbpf" }

[features]
default = []
probes = []
